Delete unnecessary log files

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -29,35 +29,37 @@ c_counter=0
 while getopts ':a:b:c:' opt; do
     case $opt in
         a)  
-            if [[ $date_before != "" ]]; then
-                echo "errror multiple -a options" >&2
-                exit 1
-            fi
-            date_before=${args[counter_for_getopts]}
-            # Validate datetime format
-            if [[ -n "$date_before" ]]; then
-                if ! date -d "$date_before" +"%YYYY-%mm-%dd %HH:%MM:%SS" >/dev/null 2>&1; then
-                    # echo "error invalid datetime format for date_before" >&2
-                    exit 1
-                fi
-            fi
-            a_counter=$((a_counter + 1)) ;;
-
-        b)  
-            if [[ $date_after != "" ]]; then
-                echo "errror multiple -b options" >&2
-                exit 1
-            fi
+            # if [[ $date_after != "" ]]; then
+            #     echo "errror multiple -b options" >&2
+            #     exit 1
+            # fi
+            # echo "date_after: ${args[counter_for_getopts]}"
             date_after=${args[counter_for_getopts]}
             if [[ -n "$date_after" ]]; then
-                if [[ -n "$date_after" ]]; then
-                    if ! date -d "$date_after" +"%YYYY-%mm-%dd %HH:%MM:%SS" >/dev/null 2>&1; then
-                        # echo "error invalid datetime format for date_after" >&2
-                        exit 1
-                    fi
+                if (! (date -d "$date_after" +"%Y-%M-%D %H:%M:%S" >/dev/null 2>&1)); then
+                    echo "error invalid datetime format for date_after" >&2
+                    exit 1
+                    # echo "$date_after"
                 fi
             fi
             b_counter=$((b_counter + 1)) ;;
+            
+        b)  
+            # if [[ $date_before != "" ]]; then
+            #     echo "errror multiple -a options" >&2
+            #     exit 1
+            # fi
+            # echo "date_before: ${args[counter_for_getopts]}"
+            date_before=${args[counter_for_getopts]}
+            # Validate datetime format
+            if [[ -n "$date_before" ]]; then
+                if (! (date -d "$date_before" +"%Y-%m-%d %H:%M:%S" >/dev/null 2>&1)); then
+                    echo "error invalid datetime format for date_before" >&2
+                    exit 1
+                    # echo "$date_before"
+                fi
+            fi
+            a_counter=$((a_counter + 1)) ;;
 
         c)  
             if [[ $currency != "" ]]; then
@@ -78,7 +80,7 @@ while getopts ':a:b:c:' opt; do
             exit 1 ;;
     esac
     counter_of_args=$((counter_of_args + 2))
-    counter_for_getopts=$((counter_for_getopts + 2))
+    counter_for_getopts=$((counter_for_getopts + 1))
 done
 
 listcurrencyvalue=0
@@ -117,10 +119,10 @@ if (( listcurrencyvalue > 1 || listvalue > 1 || statusvalue > 1 || profitvalue >
     exit 1
 fi
 
-if (( date_after < date_before )); then
-    echo "error date_after is earlier than date_before" >&2
-    exit 1
-fi
+# if [ "$(date -d "$date_after" +%s)" -lt "$(date -d "$date_before" +%s)" ]; then
+#     echo "error date_after is earlier than date_before" >&2
+#     exit 1
+# fi
 
 name=${args[counter_of_args]}
 if [[ ($name == "") || ($name == *.log) || ($name == *" "*) || ($name == "status") || ($name == "list-currency") || ($name == "status") || ($name == "profit")]]; then
@@ -128,11 +130,17 @@ if [[ ($name == "") || ($name == *.log) || ($name == *" "*) || ($name == "status
     exit 1
 fi
 
+lognum=1
 # Store remaining arguments in the "log" array
 for (( i = counter_of_args + 1; i < count_of_args; i++ )); do
-    lognum=$((i))
-    log[lognum]=${args[i]}
-    echo "${log[lognum]}"
+    if [[ ! -f "${args[i]}" ]]; then
+        echo "error file ${args[i]} does not exist" >&2
+        exit 1
+    else
+        log[lognum]=${args[i]}
+        # echo "$lognum = ${log[lognum]}"
+        lognum=$((lognum + 1))
+    fi
 done
 
 # echo "name: $name"
@@ -144,66 +152,73 @@ done
 
 
 # Process each log file
-for ((i = 1; i <= ${#log[@]}; i++)); do
+for (( i = 1; i <= ${#log[@]}; i++ )); do
     {
     # Decompress .gz files if necessary
-    if [[ "${log[i]}" == *".gz" ]]; then
+    if [[ "${log[i]}" =~ \.gz$ ]]; then
         # echo "${log[i]}"
-        gunzip -c "${log[i]}" #| awk -F";" '{if (( $0 ~ /^[^;]+;[^;]+;[A-Z]{3};[+-]?[0-9]+([.][0-9]+)?$/ ) && ($1 ~ /^[^;]+$/) && (date -d $2 +"%Y-%m-%d %H:%M:%S") && ($2 ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$/) && (length($3) == 3) && ($4 ~ /^[+-]?[0-9]+([.][0-9]+)?$/)) print $0; else {exit 1;} }' 
+        gunzip -c "${log[i]}" | awk -F";" '{if (( $0 ~ /^[^;]+;[^;]+;[A-Z]{3};[+-]?[0-9]+([.][0-9]+)?$/ ) && ($1 ~ /^[^;]+$/) && (date -d $2 +"%Y-%m-%d %H:%M:%S") && ($2 ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$/) && (length($3) == 3) && ($4 ~ /^[+-]?[0-9]+([.][0-9]+)?$/)); else {exit 1;} }' 
+        gunzip -c "${log[i]}"
     else
         # echo "${log[i]}"
-        cat "${log[i]}" #| awk -F";" '{if (( $0 ~ /^[^;]+;[^;]+;[A-Z]{3};[+-]?[0-9]+([.][0-9]+)?$/ ) && ($1 ~ /^[^;]+$/) && (date -d $2 +"%Y-%m-%d %H:%M:%S") && ($2 ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$/) && (length($3) == 3) && ($4 ~ /^[+-]?[0-9]+([.][0-9]+)?$/)) print $0; else {exit 1;} }' 
+        cat "${log[i]}" | awk -F";" '{if (( $0 ~ /^[^;]+;[^;]+;[A-Z]{3};[+-]?[0-9]+([.][0-9]+)?$/ ) && ($1 ~ /^[^;]+$/) && (date -d $2 +"%Y-%m-%d %H:%M:%S") && ($2 ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$/) && (length($3) == 3) && ($4 ~ /^[+-]?[0-9]+([.][0-9]+)?$/)); else {exit 1;} }'
+        cat "${log[i]}"
     fi
-    } #|
-    # {
+    } |
+
+    {
+        awk -F";" '{if (( $0 ~ /^[^;]+;[^;]+;[A-Z]{3};[+-]?[0-9]+([.][0-9]+)?$/ ) && ( $1 ~ /^[^;]+$/ ) && ( date -d $2 +"%Y-%m-%d %H:%M:%S" ) && ( $2 ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$/ ) && ( length($3) == 3 ) && ( $4 ~ /^[+-]?[0-9]+([.][0-9]+)?$/ )) print $0; else {exit 1;} }'
+    } |
+
+    {
     # # #    awk '{print $0}'
     # # # Perform different actions based on the provided arguments
-    # if (( ( listcurrencyvalue == 0 && listvalue == 0 && statusvalue == 0 && profitvalue == 0 ) || (listvalue == 1) )); then
-    #     # Print lines containing the specified name
-    #     # for logs in "${log[@]}"; do
-    #         if [[ -n "$currency" ]]; then
-    #             if [[ (-n "$date_before") && (-n "$date_after") ]]; then
-    #                 awk -F";" -v name="$name" -v currency="$currency" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 >= date_before) && ($2 <= date_after)) print $0; }' 
-    #             elif [[ -n "$date_before" ]]; then
-    #                 awk -F";" -v name="$name" -v currency="$currency" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 >= date_before)) print $0; }' 
-    #             elif [[ -n "$date_after" ]]; then
-    #                 awk -F";" -v name="$name" -v currency="$currency" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 <= date_after)) print $0; }' 
-    #             else
-    #                 awk -F";" -v name="$name" -v currency="$currency" '{ if (($1 == name) && ($3 ~ currency)) print $0; }' 
-    #             fi
-    #         else
-    #             if [[ (-n "$date_before") && (-n "$date_after") ]]; then
-    #                 awk -F";" -v name="$name" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($2 >= date_before) && ($2 <= date_after)) print $0; }'
-    #             elif [[ -n "$date_before" ]]; then
-    #                 awk -F";" -v name="$name" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($2 >= date_before)) print $0; }'
-    #             elif [[ -n "$date_after" ]]; then
-    #                 awk -F";" -v name="$name" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($2 <= date_after)) print $0; }'
-    #             else
-    #                 awk -F";" -v name="$name" '{ if ($1 == name) print $0; }' 
-    #             fi
-    #         fi
-    #     # done
+    if (( ( listcurrencyvalue == 0 && listvalue == 0 && statusvalue == 0 && profitvalue == 0 ) || (listvalue == 1) )); then
+        # Print lines containing the specified name
+        # for logs in "${log[@]}"; do
+            if [[ -n "$currency" ]]; then
+                if [[ (-n "$date_before") && (-n "$date_after") ]]; then
+                    awk -F";" -v name="$name" -v currency="$currency" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 >= date_before) && ($2 <= date_after)) print $0; }' 
+                elif [[ -n "$date_before" ]]; then
+                    awk -F";" -v name="$name" -v currency="$currency" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 >= date_before)) print $0; }' 
+                elif [[ -n "$date_after" ]]; then
+                    awk -F";" -v name="$name" -v currency="$currency" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 <= date_after)) print $0; }' 
+                else
+                    awk -F";" -v name="$name" -v currency="$currency" '{ if (($1 == name) && ($3 ~ currency)) print $0; }' 
+                fi
+            else
+                if [[ (-n "$date_before") && (-n "$date_after") ]]; then
+                    awk -F";" -v name="$name" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($2 >= date_before) && ($2 <= date_after)) print $0; }'
+                elif [[ -n "$date_before" ]]; then
+                    awk -F";" -v name="$name" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($2 >= date_before)) print $0; }'
+                elif [[ -n "$date_after" ]]; then
+                    awk -F";" -v name="$name" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($2 <= date_after)) print $0; }'
+                else
+                    awk -F";" -v name="$name" '{ if ($1 == name) print $0; }' 
+                fi
+            fi
+        # done
 
-    # elif (( listcurrencyvalue == 1 )); then
+    elif (( listcurrencyvalue == 1 )); then
 
-    #     # declare -a allcurrency
-    #     # Print the third column of lines containing the specified name
-    #     awk -F";" -v name="$name" '{ if ($1 == name) print $3; }' | sort -u
+        # declare -a allcurrency
+        # Print the third column of lines containing the specified name
+        awk -F";" -v name="$name" '{ if ($1 == name) print $3; }' | sort -u
         
             
-    # elif (( statusvalue == 1 )); then
+    elif (( statusvalue == 1 )); then
 
-    #     echo "status"
+        echo "status"
 
-    # elif (( profitvalue == 1 )); then
+    elif (( profitvalue == 1 )); then
 
-    #     echo "profit"
+        echo "profit"
 
-    # else
-    #     echo "error invalid arguments" >&2
-    #     exit 1
-    # fi
-    # }
+    else
+        echo "error invalid arguments" >&2
+        exit 1
+    fi
+    }
 done
 
 exit 0
