Remove unnecessary log files and update command handling

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -16,26 +16,28 @@ fi
 args=("$@")
 
 counter_for_getopts=1
-while getopts ':a:b:c:' opt; do
+while getopts ':a:b:c' opt; do
   case $opt in
     a)  
-        echo "a = ${args[counter_for_getopts]}"
+        date_before=${args[counter_for_getopts]}
          ;;
     b)  
-        echo "b = ${args[counter_for_getopts]}"
+        date_after=${args[counter_for_getopts]}
          ;;
     c) 
-        echo "c = $2"
+        currency=${args[counter_for_getopts]}
          ;;
     *)  
-        echo "errror invalid flag" >&2
+        echo "errror invalid flag" >&2 #echo
         exit 1 ;;
   esac
   counter_of_args=$((counter_of_args + 2))
   counter_for_getopts=$((counter_for_getopts + 2))
 done
 
-echo "counter_for_getopts = $counter_for_getopts" >&2
+echo "date_before = $date_before" >&2 #echo
+echo "date_after = $date_after" >&2 #echo
+echo "currency = $currency" >&2 #echo
 
 listcurrencyvalue=0
 listvalue=0
@@ -46,46 +48,45 @@ for arg in "${args[@]}"; do
     if [[ $arg == "list-currency" ]]; then
         listcurrencyvalue=1
         counter_of_args=$((counter_of_args + 1))
-        echo "print list-currency" >&2
+        echo "command = list-currency" >&2 #echo
         break
     fi
     
     if [[ $arg == "list" ]]; then
         listvalue=1
         counter_of_args=$((counter_of_args + 1))
-        echo "print list" >&2
+        echo "command = list" >&2 #echo
         break
     fi
 
     if [[ $arg == "status" ]]; then
         statusvalue=1
         counter_of_args=$((counter_of_args + 1))
-        echo "print status" >&2
+        echo "command = status" >&2 #echo
         break
     fi
 
     if [[ $arg == "profit" ]]; then
         profitvalue=1
         counter_of_args=$((counter_of_args + 1))
-        echo "print profit" >&2
+        echo "command = profit" >&2 #echo
         break
     fi    
 done
 
 if [[ ($listcurrencyvalue -eq 0) && ($listvalue -eq 0) && ($statusvalue -eq 0) && ($profitvalue -eq 0) ]]; then
-    echo "print list" >&2
+    echo "no command = list" >&2 #echo
 fi
 
 name=${args[$counter_of_args]}
 counter_of_args=$((counter_of_args + 1))
 
-# echo "count_of_args = $count_of_args" >&2
-echo "name = $name" >&2
+echo "name = $name" >&2 #echo
 
-for (( i = counter_of_args; i < $count_of_args; i++ )); do
+for (( i = counter_of_args; i < count_of_args; i++ )); do
     lognum=$((i - counter_of_args + 1))
-    log[$lognum]=${args[$i]}
-    echo "log$lognum = ${log[lognum]}" >&2
+    log[lognum]=${args[$i]}
+    echo "log$lognum = ${log[lognum]}" >&2 #echo
 done
 
 exit 0
