Update status and profit calculations

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -36,8 +36,8 @@ while getopts ':a:b:c:' opt; do
             date_before=${args[counter_for_getopts]}
             # Validate datetime format
             if [[ -n "$date_before" ]]; then
-                if ! date -d "$date_before" +"%Y-%m-%d %H:%M:%S" >/dev/null 2>&1; then
-                    echo "error invalid datetime format for date_before" >&2
+                if ! date -d "$date_before" +"%YYYY-%mm-%dd %HH:%MM:%SS" >/dev/null 2>&1; then
+                    # echo "error invalid datetime format for date_before" >&2
                     exit 1
                 fi
             fi
@@ -51,8 +51,8 @@ while getopts ':a:b:c:' opt; do
             date_after=${args[counter_for_getopts]}
             if [[ -n "$date_after" ]]; then
                 if [[ -n "$date_after" ]]; then
-                    if ! date -d "$date_after" +"%Y-%m-%d %H:%M:%S" >/dev/null 2>&1; then
-                        echo "error invalid datetime format for date_after" >&2
+                    if ! date -d "$date_after" +"%YYYY-%mm-%dd %HH:%MM:%SS" >/dev/null 2>&1; then
+                        # echo "error invalid datetime format for date_after" >&2
                         exit 1
                     fi
                 fi
@@ -81,8 +81,6 @@ while getopts ':a:b:c:' opt; do
     counter_for_getopts=$((counter_for_getopts + 2))
 done
 
-
-
 listcurrencyvalue=0
 listvalue=0
 statusvalue=0
@@ -92,90 +90,48 @@ profitvalue=0
 for arg in "${args[@]}"; do
     case $arg in
         "list")
-            listvalue=1
+            listvalue=$((listvalue + 1))
             counter_of_args=$((counter_of_args + 1))
             break
             ;;
         "list-currency")
-            listcurrencyvalue=1
+            listcurrencyvalue=$((listcurrencyvalue + 1))
             counter_of_args=$((counter_of_args + 1))
             break
             ;;
         "status")
-            statusvalue=1
+            statusvalue=$((statusvalue + 1))
             counter_of_args=$((counter_of_args + 1))
             break
             ;;
         "profit")
-            profitvalue=1
+            profitvalue=$((profitvalue + 1))
             counter_of_args=$((counter_of_args + 1))
             break
             ;;
     esac
 done
 
-name=${args[counter_of_args]}
-if [[ ($name == "") || ($name == *.log) || ($name == *" "*) || ($name == "status") || ($name == "list-currency") || ($name == "status") || ($name == "profit")]]; then
-    echo "errror no name provided" >&2
+if (( listcurrencyvalue > 1 || listvalue > 1 || statusvalue > 1 || profitvalue > 1 )); then
+    echo "error multiple arguments" >&2
     exit 1
 fi
 
-# for curr in "${currency[@]}"; do
-#     echo "$curr"
-# done
+if (( date_after < date_before )); then
+    echo "error date_after is earlier than date_before" >&2
+    exit 1
+fi
+
+name=${args[counter_of_args]}
+if [[ ($name == "") || ($name == *.log) || ($name == *" "*) || ($name == "status") || ($name == "list-currency") || ($name == "status") || ($name == "profit")]]; then
+    echo "error no name provided" >&2
+    exit 1
+fi
 
 # Store remaining arguments in the "log" array
 for (( i = counter_of_args + 1; i < count_of_args; i++ )); do
     lognum=$((i))
-    # val=0
-    # for log_item in "${log[@]}"; do
-    #     if [[ ("${args[lognum]}" == *"$log_item"*) ]]; then
-    #         val=1
-    #         break
-    #     fi
-    # done
-    # if (( val == 1 )); then
-    #     break   
-    # fi    
     log[lognum]=${args[i]}
-done
-
-# Process each log file
-for ((i = 1; i <= ${#log[@]}; i++)); do
-
-    # Decompress .gz files if necessary
-    
-    if [[ "${log[i]}" == *".gz" ]]; then
-        # echo "${log[i]}"
-        gz="$(gzip -dc "${log[i]}")"
-        log[i]="${log[i]%.gz}"
-        
-        # echo "${log[i]}"
-    fi
-
-    # if [[ "${log[i]}" == *" "* ]]; then
-    #     echo "errror space in log file" >&2
-    #     exit 1
-    # fi
-
-done
-
-for logs in "${log[@]}"; do
-    if [[ ! -f "$logs" ]]; then
-        echo "errror log file not found" >&2
-        exit 1
-    fi
-    # Validate datetime format
-    # awk -F";" ' { if ( $0 ~ /^[^;]+;[^;]+;[A-Z]{3};[+-]?[0-9]+([.][0-9]+)?$/ ); else { exit 1; } }' "$logs"
-    # awk -F";" '{ if ($1 ~ /^[^;]+$/); else { exit 1; } }' "$logs"
-    # awk -F";" '{ if (date -d $2 +"%YYYY-%mm-%dd %HH:%MM:%SS"); else { exit 1; } }' "$logs"
-    # awk -F";" '{ if ($2 ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$/); else { exit 1; } }' "$logs"
-    # awk -F";" '{ if (length($3) == 3); else { exit 1; } }' "$logs"
-    # awk -F";" '{ if ($4 ~ /^[+-]?[0-9]+([.][0-9]+)?$/); else { exit 1; } }' "$logs"
-
-    awk -F";" '{if (( $0 ~ /^[^;]+;[^;]+;[A-Z]{3};[+-]?[0-9]+([.][0-9]+)?$/ ) && ($1 ~ /^[^;]+$/) && (date -d $2 +"%YYYY-%mm-%dd %HH:%MM:%SS") && ($2 ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$/) && (length($3) == 3) && ($4 ~ /^[+-]?[0-9]+([.][0-9]+)?$/)); else {exit 1;} }' "$logs"
-    
-    
 done
 
 # echo "name: $name"
@@ -185,63 +141,66 @@ done
 # echo "date_after: $date_after"
 # echo "command:\nlistcurrency: $listcurrencyvalue\nlist: $listvalue\nstatus: $statusvalue\nprofit: $profitvalue"
 
-# Perform different actions based on the provided arguments
-if (( ( listcurrencyvalue == 0 && listvalue == 0 && statusvalue == 0 && profitvalue == 0 ) || (listvalue == 1) )); then
-    # Print lines containing the specified name
-    
-    
-    for logs in "${log[@]}"; do
-        if [[ -n "$currency" ]]; then
-            if [[ (-n "$date_before") && (-n "$date_after") ]]; then
-                awk -F";" -v name="$name" -v currency="$currency" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 >= date_before) && ($2 <= date_after)) print $0;  >/dev/null 2>&1; }' "$logs"
-            elif [[ -n "$date_before" ]]; then
-                awk -F";" -v name="$name" -v currency="$currency" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 >= date_before)) print $0;  >/dev/null 2>&1; }' "$logs"
-            elif [[ -n "$date_after" ]]; then
-                awk -F";" -v name="$name" -v currency="$currency" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 <= date_after)) print $0;  >/dev/null 2>&1; }' "$logs"
+
+# Process each log file
+for ((i = 1; i <= ${#log[@]}; i++)); do
+    {
+    # Decompress .gz files if necessary
+    if [[ "${log[i]}" == *".gz" ]]; then
+        gzip -d "${log[i]}" | awk -F";" '{if (( $0 ~ /^[^;]+;[^;]+;[A-Z]{3};[+-]?[0-9]+([.][0-9]+)?$/ ) && ($1 ~ /^[^;]+$/) && (date -d $2 +"%Y-%m-%d %H:%M:%S") && ($2 ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$/) && (length($3) == 3) && ($4 ~ /^[+-]?[0-9]+([.][0-9]+)?$/)) print $0; else {exit 1;} }' 
+    else
+        cat "${log[i]}" | awk -F";" '{if (( $0 ~ /^[^;]+;[^;]+;[A-Z]{3};[+-]?[0-9]+([.][0-9]+)?$/ ) && ($1 ~ /^[^;]+$/) && (date -d $2 +"%Y-%m-%d %H:%M:%S") && ($2 ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$/) && (length($3) == 3) && ($4 ~ /^[+-]?[0-9]+([.][0-9]+)?$/)) print $0; else {exit 1;} }' 
+    fi
+    } |
+    {
+    #    awk '{print $0}'
+    # Perform different actions based on the provided arguments
+    if (( ( listcurrencyvalue == 0 && listvalue == 0 && statusvalue == 0 && profitvalue == 0 ) || (listvalue == 1) )); then
+        # Print lines containing the specified name
+        # for logs in "${log[@]}"; do
+            if [[ -n "$currency" ]]; then
+                if [[ (-n "$date_before") && (-n "$date_after") ]]; then
+                    awk -F";" -v name="$name" -v currency="$currency" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 >= date_before) && ($2 <= date_after)) print $0; }' 
+                elif [[ -n "$date_before" ]]; then
+                    awk -F";" -v name="$name" -v currency="$currency" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 >= date_before)) print $0; }' 
+                elif [[ -n "$date_after" ]]; then
+                    awk -F";" -v name="$name" -v currency="$currency" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 <= date_after)) print $0; }' 
+                else
+                    awk -F";" -v name="$name" -v currency="$currency" '{ if (($1 == name) && ($3 ~ currency)) print $0; }' 
+                fi
             else
-                awk -F";" -v name="$name" -v currency="$currency" '{ if (($1 == name) && ($3 ~ currency)) print $0; }' "$logs"
+                if [[ (-n "$date_before") && (-n "$date_after") ]]; then
+                    awk -F";" -v name="$name" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($2 >= date_before) && ($2 <= date_after)) print $0; }'
+                elif [[ -n "$date_before" ]]; then
+                    awk -F";" -v name="$name" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($2 >= date_before)) print $0; }'
+                elif [[ -n "$date_after" ]]; then
+                    awk -F";" -v name="$name" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($2 <= date_after)) print $0; }'
+                else
+                    awk -F";" -v name="$name" '{ if ($1 == name) print $0; }' 
+                fi
             fi
-        else
-            if [[ (-n "$date_before") && (-n "$date_after") ]]; then
-                awk -F";" -v name="$name" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($2 >= date_before) && ($2 <= date_after)) print $0;  >/dev/null 2>&1; }' "$logs"
-            elif [[ -n "$date_before" ]]; then
-                awk -F";" -v name="$name" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($2 >= date_before)) print $0;  >/dev/null 2>&1; }' "$logs"
-            elif [[ -n "$date_after" ]]; then
-                awk -F";" -v name="$name" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($2 <= date_after)) print $0;  >/dev/null 2>&1; }' "$logs"
-            else
-                awk -F";" -v name="$name" '{ if ($1 == name) print $0; }' "$logs"
-            fi
-        fi
-    done
+        # done
 
-elif (( listcurrencyvalue == 1 )); then
+    elif (( listcurrencyvalue == 1 )); then
 
-    # declare -a allcurrency
-    # Print the third column of lines containing the specified name
-    for logs in "${log[@]}"; do
-        # echo "logs: $logs"
-        awk -F";" -v name="$name" '{ if ($1 == name) print $3; }' "$logs" | sort -u
-    done
+        # declare -a allcurrency
+        # Print the third column of lines containing the specified name
+        awk -F";" -v name="$name" '{ if ($1 == name) print $3; }' | sort -u
         
+            
+    elif (( statusvalue == 1 )); then
 
-        
-        
-        
-        
-        
- 
-elif (( statusvalue == 1 )); then
+        echo "status"
 
-    echo "status"
+    elif (( profitvalue == 1 )); then
 
-elif (( profitvalue == 1 )); then
+        echo "profit"
 
-    echo "profit"
-
-else
-    echo "error invalid arguments" >&2
-    exit 1
-
-fi
+    else
+        echo "error invalid arguments" >&2
+        exit 1
+    fi
+    }
+done
 
 exit 0
