Fix currency validation and error handling in script

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -23,7 +23,7 @@ a_counter=0
 b_counter=0
 c_counter=0
 declare -a allcurrency
-declare -a currency
+# declare -a currency
 
 # Parse command-line options using getopts
 while getopts ':a:b:c:' opt; do
@@ -60,20 +60,16 @@ while getopts ':a:b:c:' opt; do
             b_counter=$((b_counter + 1)) ;;
 
         c)  
-            val=0
-            if (( ${#currency[@]} > 0 )); then
-                for curr in "${currency[@]}"; do
-                    if [[ "${args[counter_of_args + 1]}" == *"$curr"* ]]; then
-                        val=1
-                    fi
-                done
+            if [[ $currency != "" ]]; then
+                echo "errror multiple -c options" >&2
+                exit 1
             fi
-            if (( val == 0 )); then
-                currency[c_counter]="${args[counter_of_args + 1]}"
-                c_counter=$((c_counter + 1))
-            fi
-            if [[ "${#currency[c_counter - 1]}" != 3 ]]; then
-                echo "errror invalid currency" >&2
+            
+            currency="${args[counter_of_args + 1]}"
+            c_counter=$((c_counter + 1))
+                
+            if [[ ${#currency} -ne 3 ]]; then
+                echo "error invalid currency length" >&2
                 exit 1
             fi
             ;;
@@ -190,16 +186,16 @@ done
 if (( ( listcurrencyvalue == 0 && listvalue == 0 && statusvalue == 0 && profitvalue == 0 ) || (listvalue == 1) )); then
     # Print lines containing the specified name
     
-    if (( ${#currency[@]} > 0 )); then
+    if [[ -n "$currency" ]]; then
         for logs in "${log[@]}"; do
             if [[ (-n "$date_before") && (-n "$date_after") ]]; then
-                awk -F";" -v name="$name" -v currency="${currency[*]}" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 =~ currency) && ($2 >= date_before) && ($2 <= date_after)) print $0; }' "$logs"
+                awk -F";" -v name="$name" -v currency="$currency" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 >= date_before) && ($2 <= date_after)) print $0; }' "$logs"
             elif [[ -n "$date_before" ]]; then
-                awk -F";" -v name="$name" -v currency="${currency[*]}" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 =~ currency) && ($2 >= date_before)) print $0; }' "$logs"
+                awk -F";" -v name="$name" -v currency="$currency" -v date_before="$(date -d "$date_before" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 >= date_before)) print $0; }' "$logs"
             elif [[ -n "$date_after" ]]; then
-                awk -F";" -v name="$name" -v currency="${currency[*]}" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 =~ currency) && ($2 <= date_after)) print $0; }' "$logs"
+                awk -F";" -v name="$name" -v currency="$currency" -v date_after="$(date -d "$date_after" +"%Y-%m-%d %H:%M:%S")" '{ if (($1 == name) && ($3 == currency) && ($2 <= date_after)) print $0; }' "$logs"
             else
-                awk -F";" -v name="$name" -v currency="${currency[*]}" '{ if (($1 == name) && ($3 ~ currency)) print $0; }' "$logs"
+                awk -F";" -v name="$name" -v currency="$currency" '{ if (($1 == name) && ($3 ~ currency)) print $0; }' "$logs"
             fi
         done
     else
